name: bignum
description: Big Number library for Dart
version: 0.0.3
author: Adam Singer <financeCoding@gmail.com>
homepage: https://github.com/Dartist/dart-bignum
dev_dependencies:
  unittest: ">=0.5.0+1 <0.5.1"
